# QUERY 1

SELECT BDATE, ADDRESS
FROM EMPLOYEE
WHERE FNAME= 'JOHN' AND MINIT= 'B' AND LNAME= 'SMITH';

# QUERY 2

SELECT E.FNAME, E.LNAME, S.FNAME, S.LNAME
FROM EMPLOYEE AS E, EMPLOYEE AS S
WHERE E.SUPER_SSN= S.SSN;

# CONSULTAR A TABELA
SELECT * FROM EMPLOYEE;

# DISCRIÇÃO DAS VARIÁVEIS DA TABELA
DESCRIBE EMPLOYEE;

