#QUERY 0
SELECT BDATE, ADDRESS
FROM EMPLOYEE
WHERE FNAME='JOHN' AND MINIT= 'B' AND LNAME='SMITH';

#QUERY 1
SELECT FNAME, LNAME, ADDRESS
FROM EMPLOYEE, DEPARTMENT
WHERE DNAME= 'RESEARCH' AND DNUMBER= 'DNO';

#QUERY 2
SELECT PNUMBER, DNUM, LNAME, ADDRESS, BDATE
FROM PROJECT, DEPARTMENT, EMPLOYEE
WHERE DNUM= DNUMBER AND MGR_SSN= SSN AND PLOCATION='STAFFORD';

#QUERY 3
SELECT E.FNAME, E.LNAME, S.FNAME, S.LNAME
FROM EMPLOYEE AS E, EMPLOYEE AS S
WHERE E.SUPER_SSN= S.SSN; 

#QUERY 4
SELECT SSN
FROM EMPLOYEE;

#QUERY 5
SELECT SSN, DNAME
FROM EMPLOYEE, DEPARTMENT;

#QUERY 6
SELECT *
FROM EMPLOYEE
WHERE DNO=5;

#QUERY 7
SELECT *
FROM EMPLOYEE, DEPARTMENT
WHERE DNAME= 'RESEARCH' AND DNO= DNUMBER;

#QUERY 8
SELECT ALL SALARY
FROM EMPLOYEE;

#QUERY 9
SELECT DISTINCT SALARY
FROM EMPLOYEE;