INSERT INTO EMPLOYEE
VALUES ('Richard', 'K', 'Marini','653298653', '1962-12-30', '98
Oak Forest, Katy, TX', 'M', 37000,'653298653', 4);

CREATE TABLE WORKS_ON_INFO(
EMP_NAME VARCHAR(15),
PROJ_NAME VARCHAR(15),
HOURS_PER_WEEK DECIMAL(3,1)
);

INSERT INTO WORKS_ON_INFO(EMP_NAME, PROJ_NAME, HOURS_PER_WEEK)
SELECT E.LNAME, P.PNAME, W.HOURS
FROM PROJECT P, WORKS_ON W, EMPLOYEE E
WHERE P.PNUMBER= W.PNO AND W.ESSN=E.SSN;

CREATE TABLE D5EMPS LIKE EMPLOYEE
(SELECT E. * FROM EMPLOYEE AS E
WHERE E.DNO=5) WITH DATA;

DELETE FROM EMPLOYEE 
WHERE LNAME='Brown';

DELETE FROM EMPLOYEE
WHERE SSN='123456789';

DELETE FROM EMPLOYEE
WHERE DNO=5;

DELETE FROM EMPLOYEE;

UPDATE PROJECT
SET PLOCATION='Bellaire', DNUM=5
WHERE PNUMBER=10;

UPDATE EMPLOYEE
SET SALARY=SALARY*1.1
WHERE DNO=5;