#IMPLEMENTAÇÃO USANDO CREATE, ALTER E DROP
#IMPLEMENTAÇÃO USANDO CREATE, ALTER E DROP
 
#QUERY 1
USE TABELA;
CREATE TABLE WORKS_OUT(
Essn char(9) not null,
Pno int not null,
Hours decimal(3,1) not null,
PRIMARY KEY(Essn, Pno),
FOREIGN KEY(Essn) REFERENCES EMPLOYEE(Ssn)
);

SELECT * FROM WORKS_OUT;



