#IMPLEMENTAÇÃO USANDO SELECT-FROM-WHERE

SELECT * FROM EMPLOYEE;
#QUERY 0
SELECT BDATE, ADDRESS
FROM EMPLOYEE
WHERE FNAME='JOHN' AND MINIT='B' AND LNAME='SMITH';

#QUERY 8
SELECT FNAME, LNAME, ADDRESS
FROM EMPLOYEE, DEPARTMENT
WHERE DNAME='RESEARCH' AND DNUMBER=DNO;

#QUERY 9
SELECT PNUMBER, DNUM, LNAME, ADDRESS BDATE
FROM PROJECT, DEPARTMENT, EMPLOYEE
WHERE DNUM=DNUMBER AND MGR_SSN=SSN AND PLOCATION='STAFFORD';

#QUERY 10
SELECT E.FNAME, E.LNAME, S.FNAME, S.LNAME
FROM EMPLOYEE AS E, EMPLOYEE AS S
WHERE E.SUPER_SSN=S.SSN;

#QUERY 11
SELECT SSN
FROM EMPLOYEE;

#QUERY 12
SELECT SSN, DNAME
FROM EMPLOYEE, DEPARTMENT;

#QUERY 13
SELECT * 
FROM EMPLOYEE
WHERE DNO=5;

#QUERY 14
SELECT *
FROM EMPLOYEE, DEPARTMENT 
WHERE DNAME='RESEARCH' AND DNO=DNUMBER;

#QUERY 15
SELECT ALL SALARY
FROM EMPLOYEE;

#QUERY 16
SELECT DISTINCT SALARY
FROM EMPLOYEE;




