CREATE DATABASE MYDB;
-- DB DE GERENCIAMENTO DE PROJETOS

CREATE TABLE USUARIOS(
FNAME VARCHAR(20) NOT NULL,
LNAME VARCHAR(20) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
SENHA VARCHAR(200) NOT NULL
);

ALTER TABLE USUARIOS
ADD  ID INT PRIMARY KEY;

CREATE TABLE PROJETOS(
ID INT PRIMARY KEY,
FNAME VARCHAR(20) NOT NULL,
LNAME VARCHAR(20) NOT NULL,
DATA_INICIO DATE NOT NULL,
DESCRICAO TEXT
);

CREATE TYPE STATUS AS ENUM('Pendente', 'Em andamento', 'Concluído');

CREATE TABLE TAREFAS(
ID INT PRIMARY KEY,
PRAZO DATE NOT NULL,
DESCRICAO TEXT,
STATUS STATUS,
PROJETO_ID INT NOT NULL,
FOREIGN KEY(PROJETO_ID) REFERENCES PROJETOS(ID)
);

--ALTER TABLE TAREFAS
--ADD STATUS AS ENUM('Pendente', 'Em andamento', 'Concluído') NOT NULL;

CREATE TABLE EQUIPE(
ID INT PRIMARY KEY,
FNAME VARCHAR(20) NOT NULL,
LNAME VARCHAR(20) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
FUNCAO VARCHAR(50) NOT NULL
);

CREATE TABLE TAREFAS_ATRIBUIDAS(
ID INT PRIMARY KEY,
COMENTARIO TEXT NOT NULL,
EQUIPE_ID INT NOT NULL,
TAREFA_ID INT NOT NULL,
FOREIGN KEY(EQUIPE_ID) REFERENCES EQUIPE(ID),
FOREIGN KEY(TAREFA_ID) REFERENCES TAREFAS(ID)
);

INSERT INTO USUARIOS (FNAME, LNAME, EMAIL, SENHA)
VALUES ('Luciana', 'Martins', 'luciana@email', '1234lulu');

INSERT INTO PROJETOS (FNAME, LNAME, DATA_INICIO, DESCRICAO)
VALUES ('Luciana', 'Martins', '2023-04-01', 'Primeira semana de descricao do projeto');

select * from TAREFAS_ATRIBUIDAS;

INSERT INTO TAREFAS (PRAZO, DESCRICAO, PROJETO_ID, STATUS)
VALUES ('2023-05-01', 'Projeto 1', 1, 'Em andamento');

INSERT INTO EQUIPE (FNAME, LNAME, EMAIL, FUNCAO)
VALUES ('Luciana', 'Martins', 'luciana@email', 'Analista de Dados');

INSERT INTO TAREFAS_ATRIBUIDAS (COMENTARIO, EQUIPE_ID, TAREFA_ID)
VALUES ('Primeira etapa de AED concluída', 1, 1);
