--IMPLEMENTAÇÃO USANDO CREATE, ALTER E DROP

--QUERY 1
CREATE TABLE WORKS_OUT(
ESSN CHAR(9) NOT NULL,
PNO INT NOT NULL,
HOURS DECIMAL(3,1) NOT NULL,
PRIMARY KEY(ESSN, PNO),
FOREIGN KEY(ESSN) REFERENCES EMPLOYEE(SSN)
);

--QUERY 2
ALTER TABLE WORKS_OUT
ADD FNAME VARCHAR(50);

--QUERY 3
ALTER TABLE WORKS_OUT
ADD LNAME VARCHAR(50);

--QUERY 4
ALTER TABLE WORKS_OUT
ADD SEX CHAR;

--QUERY 5
ALTER TABLE WORKS_OUT
DROP COLUMN HOURS;

--QUERY 6
ALTER TABLE WORKS_OUT
DROP COLUMN PNO;

--QUERY 7
SELECT * FROM WORKS_OUT;

--QUERY 8
SELECT BDATE, ADDRESS
FROM EMPLOYEE
WHERE FNAME='JOHN' AND MINIT='B' AND LNAME='SMITH';

--QUERY 9
SELECT FNAME, LNAME, ADDRESS
FROM EMPLOYEE, DEPARTMENT
WHERE DNAME='RESEARCH' AND DNUMBER=DNO;

--QUERY 10
SELECT PNUMBER, DNUM, LNAME, ADDRESS BDATE
FROM PROJECT, DEPARTMENT, EMPLOYEE
WHERE DNUM=DNUMBER AND MGR_SSN=SSN AND PLOCATION='STAFFORD';

--QUERY 11
SELECT E.FNAME, E.LNAME, S.FNAME, S.LNAME
FROM EMPLOYEE AS E, EMPLOYEE AS S
WHERE E.SUPER_SSN=S.SSN;

--QUERY 12
SELECT SSN
FROM EMPLOYEE;

--QUERY 13
SELECT SSN, DNAME
FROM EMPLOYEE, DEPARTMENT;

--QUERY 14
SELECT * 
FROM EMPLOYEE
WHERE DNO=5;

--QUERY 15
SELECT *
FROM EMPLOYEE, DEPARTMENT 
WHERE DNAME='RESEARCH' AND DNO=DNUMBER;

--QUERY 16
SELECT ALL SALARY
FROM EMPLOYEE;

--QUERY 17
SELECT DISTINCT SALARY
FROM EMPLOYEE;
