#IMPLEMENTAÇÃO USANDO CREATE, ALTER E DROP

#QUERY 5
ALTER TABLE WORKS_OUT
DROP COLUMN HOURS;

#QUERY 6
ALTER TABLE WORKS_OUT
DROP COLUMN PNO;

#QUERY 7
SELECT * FROM WORKS_OUT#QUERY 5
ALTER TABLE WORKS_OUT
DROP COLUMN HOURS;

#QUERY 6
ALTER TABLE WORKS_OUT
DROP COLUMN PNO;

#QUERY 7
SELECT * FROM WORKS_OUT