#IMPLEMENTAÇÃO USANDO CREATE, ALTER E DROP

#QUERY 2
ALTER TABLE WORKS_OUT
ADD FNAME VARCHAR(50);

#QUERY 3
ALTER TABLE WORKS_OUT
ADD LNAME VARCHAR(50);

#QUERY 4
ALTER TABLE WORKS_OUT
ADD SEX CHAR;ALTER TABLE WORKS_OUT
ADD FNAME VARCHAR(50);

#QUERY 3
ALTER TABLE WORKS_OUT
ADD LNAME VARCHAR(50);

#QUERY 4
ALTER TABLE WORKS_OUT
ADD SEX CHAR;